[package]
name = "nurl"
version = "0.1.0"
authors = ["figsoda <figsoda@pm.me>"]
edition = "2021"
description = ""
readme = "README.md"
homepage = "https://github.com/nix-community/nurl"
repository = "https://github.com/nix-community/nurl"
license = "MPL-2.0"
keywords = []
categories = []

[dependencies]

[profile.release]
lto = true
panic = "abort"
codegen-units = 1
